const SET_TEXT = 'SET_TEXT'
const SET_TEXTCOLOR = 'SET_TEXTCOLOR'
const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR'
const SET_FONTSIZE = 'SET_FONTSIZE'
const SET_FONTFAMILY = 'SET_FONTFAMILY'

export {
  SET_TEXT,
  SET_TEXTCOLOR,
  SET_BACKGROUND_COLOR,
  SET_FONTSIZE,
  SET_FONTFAMILY
}