const SET_TEXT = 'SET_TEXT'
const SET_TEXTCOLOR = 'SET_TEXTCOLOR'
const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR'
const SET_BACKGROUND = 'SET_BACKGROUND'
const SET_FONTSIZE = 'SET_FONTSIZE'
const SET_FONTFAMILY = 'SET_FONTFAMILY'
const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE'
const SET_STARTCOLOR = 'SET_STARTCOLOR'
const SET_ENDCOLOR = 'SET_ENDCOLOR'
const SET_DIRECTION = 'SET_DIRECTION'
const SET_GRADIENT = 'SET_GRADIENT'

export {
  SET_TEXT,
  SET_TEXTCOLOR,
  SET_BACKGROUND_COLOR,
  SET_FONTSIZE,
  SET_FONTFAMILY,
  SET_BACKGROUND_IMAGE,
  SET_STARTCOLOR,
  SET_ENDCOLOR,
  SET_DIRECTION,
  SET_GRADIENT,
  SET_BACKGROUND
}