const SET_EVENTNAME = 'SET_EVENTNAME'
const SET_LOCATION = 'SET_LOCATION'
const SET_START_DATE = 'SET_START_DATE'
const SET_END_DATE = 'SET_END_DATE'
const SET_START_TIME = 'SET_START_TIME'
const SET_END_TIME = 'SET_END_TIME'
const SET_TICKETS = 'SET_TICKETS'
const SET_VISIBILITY = 'SET_VISIBILITY'
const SET_CAPACITY = 'SET_CAPACITY'
const SET_APPROVAL = 'SET_APPROVAL'


export {
  SET_EVENTNAME,
  SET_LOCATION,
  SET_START_DATE,
  SET_END_TIME,
  SET_END_DATE,
  SET_START_TIME,
  SET_TICKETS,
  SET_VISIBILITY,
  SET_CAPACITY,
  SET_APPROVAL
}