const SET_EVENTNAME = 'SET_EVENTNAME'
const SET_LOCATION = 'SET_LOCATION'
const SET_START_DATE = 'SET_START_DATE'
const SET_END_DATE = 'SET_END_DATE'
const SET_START_TIME = 'SET_START_TIME'
const SET_END_TIME = 'SET_END_TIME'

export {
  SET_EVENTNAME,
  SET_LOCATION,
  SET_START_DATE,
  SET_END_TIME,
  SET_END_DATE,
  SET_START_TIME
}